name: Playwright Tests
# This workflow will be run on pushing and on pulling code to the main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest  # Use GitHub-hosted runner for better compatibility
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  # Add your Slack Bot Token to GitHub secrets
      SLACK_CHANNEL: '#all-testingexecutionresult'  # Replace with your Slack channel name

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Install curl in the runner
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      # Step 4: Install Maven dependencies
      - name: Install Maven Dependencies
        run: mvn install

      # Step 5: Run Playwright tests
      - name: Run Tests
        run: mvn test

      # Step 6: Upload the Extent Report as an artifact
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: src/test/reports/HTML-ExecutionReport.html

      # Step 7: Upload the Extent HTML report to Slack
      - name: Upload Extent Report to Slack
        if: always()  # Ensure this runs even if tests fail
        run: |
          # Ensure the Extent report exists
          if [ -f "src/test/reports/HTML-ExecutionReport.html" ]; then
            # Upload the Extent HTML report to Slack
            curl -F file=@src/test/reports/HTML-ExecutionReport.html \
                 -F "initial_comment=Playwright Tests completed. Here is the Extent Report." \
                 -F channels=${{ env.SLACK_CHANNEL }} \
                 -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                 https://slack.com/api/files.upload
          else
            echo "Extent report not found. Skipping upload."
          fi
